### ISSUE TITLE
Subclassing an UmbracoRestApi controller to perform my own authentication

### ISSUE THREAD

**Issue by glcheetham** [umbraco/UmbracoRestApi#17]
I'm adding an issue to try to get some feedback on my idea added on the forum [here](https://our.umbraco.org/forum/using-umbraco-and-getting-started/82340-configure-anonymous-authentication-in-umbraco-rest-api).

My problem is that I need to support anonymous authentication against certain read operations in the UmbracoRestApi. This package only supports backoffice-user authentication.

My current line of thought (untested) is that I could just subclass the `UmbracoHalController` or `ContentController`with my own web API controller implementing my own authentication, but I really need some feedback before I try incase it's a dead end.

**Comment by glcheetham** [comment]
OK, I think I've hit the first wall with this whole subclass idea. I don't think I'm going to be able to add the routes for my subclassed web api controllers.

You're using [this extension method](https://github.com/umbraco/UmbracoRestApi/blob/master/src/Umbraco.RestApi/Routing/RouteExtensions.cs#L33) to register your routes properly, but it's internal to the assembly so I can't call the method (`HttpConfiguration.MapControllerAttributeRoutes`) in my own `ApplicationEventHandler`.

I might just be able to copy and paste the code, but that idea just makes me think I'm going down more of a dead end.

**Comment by Shazwazza** [comment]
Yeah, you can't subclass the controller because all authorization attributes will be applied to all levels of inheritance, problem is the base class is attributed with `[UmbracoAuthorize]` which requires the current user that is assigned to the request to be a `UmbracoBackOfficeIdentity`

We need to overhaul the authorization/authentication process for this project. The plan should be:

* Repace the authorization filter that uses authorization policies
* Have default authorization policies in place - which do basically what we have now
* Allow for the authorization policies to be configured during startup when enabling the rest API and allow for assigning a policy to a controller/action, and allow for callbacks to run to really customize the AuthZ flow

Authentication is a slightly different story however, currently we have documented to use `app.UseUmbracoBackOfficeTokenAuth();` which of course only authenticates for back office users. If you wanted to authenticate against members or any other sort of thing you'd have to implement your own token auth endpoint. Of course I'd like to put one in for members OOTB but I need to find some time to do that. But even if that was in place now, with the current `[UmbracoAuthorize]` attribute assigned, it will not work. Though it would be possible to hack this - if you had your own token auth implementation that auth'd against whatever you want, you are responsible for creating/assigning the ticket/identity. If you were to assign/create an `UmbracoBackOfficeIdentity` even for a front-end member (hack), it would 'work'.

**Comment by Shazwazza** [comment]
You should be able to do what you need to now in the latest codebase (which will eventually be the 1.0 release)

see: https://github.com/umbraco/UmbracoRestApi/issues/30

and https://github.com/umbraco/UmbracoRestApi/issues/3
